// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transactions.proto

package transactions // import "github.com/quorumcontrol/messages/transactions"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_Unknown       TransactionType = 0
	TransactionType_SetData       TransactionType = 1
	TransactionType_SetOwnership  TransactionType = 2
	TransactionType_EstablishCoin TransactionType = 3
	TransactionType_MintCoin      TransactionType = 4
	TransactionType_Stake         TransactionType = 5
)

var TransactionType_name = map[int32]string{
	0: "Unknown",
	1: "SetData",
	2: "SetOwnership",
	3: "EstablishCoin",
	4: "MintCoin",
	5: "Stake",
}
var TransactionType_value = map[string]int32{
	"Unknown":       0,
	"SetData":       1,
	"SetOwnership":  2,
	"EstablishCoin": 3,
	"MintCoin":      4,
	"Stake":         5,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transactions_731034eeec409a34, []int{0}
}

type SetDataPayload struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataPayload) Reset()         { *m = SetDataPayload{} }
func (m *SetDataPayload) String() string { return proto.CompactTextString(m) }
func (*SetDataPayload) ProtoMessage()    {}
func (*SetDataPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_731034eeec409a34, []int{0}
}
func (m *SetDataPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataPayload.Unmarshal(m, b)
}
func (m *SetDataPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataPayload.Marshal(b, m, deterministic)
}
func (dst *SetDataPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataPayload.Merge(dst, src)
}
func (m *SetDataPayload) XXX_Size() int {
	return xxx_messageInfo_SetDataPayload.Size(m)
}
func (m *SetDataPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataPayload proto.InternalMessageInfo

func (m *SetDataPayload) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SetDataPayload) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetOwnershipPayload struct {
	Authentication       []string `protobuf:"bytes,1,rep,name=authentication,proto3" json:"authentication,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOwnershipPayload) Reset()         { *m = SetOwnershipPayload{} }
func (m *SetOwnershipPayload) String() string { return proto.CompactTextString(m) }
func (*SetOwnershipPayload) ProtoMessage()    {}
func (*SetOwnershipPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_731034eeec409a34, []int{1}
}
func (m *SetOwnershipPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOwnershipPayload.Unmarshal(m, b)
}
func (m *SetOwnershipPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOwnershipPayload.Marshal(b, m, deterministic)
}
func (dst *SetOwnershipPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOwnershipPayload.Merge(dst, src)
}
func (m *SetOwnershipPayload) XXX_Size() int {
	return xxx_messageInfo_SetOwnershipPayload.Size(m)
}
func (m *SetOwnershipPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOwnershipPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SetOwnershipPayload proto.InternalMessageInfo

func (m *SetOwnershipPayload) GetAuthentication() []string {
	if m != nil {
		return m.Authentication
	}
	return nil
}

type CoinMonetaryPolicy struct {
	Maximum              uint64   `protobuf:"varint,1,opt,name=maximum,proto3" json:"maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinMonetaryPolicy) Reset()         { *m = CoinMonetaryPolicy{} }
func (m *CoinMonetaryPolicy) String() string { return proto.CompactTextString(m) }
func (*CoinMonetaryPolicy) ProtoMessage()    {}
func (*CoinMonetaryPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_731034eeec409a34, []int{2}
}
func (m *CoinMonetaryPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinMonetaryPolicy.Unmarshal(m, b)
}
func (m *CoinMonetaryPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinMonetaryPolicy.Marshal(b, m, deterministic)
}
func (dst *CoinMonetaryPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinMonetaryPolicy.Merge(dst, src)
}
func (m *CoinMonetaryPolicy) XXX_Size() int {
	return xxx_messageInfo_CoinMonetaryPolicy.Size(m)
}
func (m *CoinMonetaryPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinMonetaryPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_CoinMonetaryPolicy proto.InternalMessageInfo

func (m *CoinMonetaryPolicy) GetMaximum() uint64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

type EstablishCoinPayload struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MonetaryPolicy       *CoinMonetaryPolicy `protobuf:"bytes,2,opt,name=monetary_policy,json=monetaryPolicy,proto3" json:"monetary_policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EstablishCoinPayload) Reset()         { *m = EstablishCoinPayload{} }
func (m *EstablishCoinPayload) String() string { return proto.CompactTextString(m) }
func (*EstablishCoinPayload) ProtoMessage()    {}
func (*EstablishCoinPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_731034eeec409a34, []int{3}
}
func (m *EstablishCoinPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstablishCoinPayload.Unmarshal(m, b)
}
func (m *EstablishCoinPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstablishCoinPayload.Marshal(b, m, deterministic)
}
func (dst *EstablishCoinPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstablishCoinPayload.Merge(dst, src)
}
func (m *EstablishCoinPayload) XXX_Size() int {
	return xxx_messageInfo_EstablishCoinPayload.Size(m)
}
func (m *EstablishCoinPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EstablishCoinPayload.DiscardUnknown(m)
}

var xxx_messageInfo_EstablishCoinPayload proto.InternalMessageInfo

func (m *EstablishCoinPayload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EstablishCoinPayload) GetMonetaryPolicy() *CoinMonetaryPolicy {
	if m != nil {
		return m.MonetaryPolicy
	}
	return nil
}

type MintCoinPayload struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MintCoinPayload) Reset()         { *m = MintCoinPayload{} }
func (m *MintCoinPayload) String() string { return proto.CompactTextString(m) }
func (*MintCoinPayload) ProtoMessage()    {}
func (*MintCoinPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_731034eeec409a34, []int{4}
}
func (m *MintCoinPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintCoinPayload.Unmarshal(m, b)
}
func (m *MintCoinPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintCoinPayload.Marshal(b, m, deterministic)
}
func (dst *MintCoinPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintCoinPayload.Merge(dst, src)
}
func (m *MintCoinPayload) XXX_Size() int {
	return xxx_messageInfo_MintCoinPayload.Size(m)
}
func (m *MintCoinPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_MintCoinPayload.DiscardUnknown(m)
}

var xxx_messageInfo_MintCoinPayload proto.InternalMessageInfo

func (m *MintCoinPayload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MintCoinPayload) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Transaction struct {
	Type                 TransactionType `protobuf:"varint,1,opt,name=type,proto3,enum=transactions.TransactionType" json:"type,omitempty"`
	Payload              *any.Any        `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactions_731034eeec409a34, []int{5}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_Unknown
}

func (m *Transaction) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*SetDataPayload)(nil), "transactions.SetDataPayload")
	proto.RegisterType((*SetOwnershipPayload)(nil), "transactions.SetOwnershipPayload")
	proto.RegisterType((*CoinMonetaryPolicy)(nil), "transactions.CoinMonetaryPolicy")
	proto.RegisterType((*EstablishCoinPayload)(nil), "transactions.EstablishCoinPayload")
	proto.RegisterType((*MintCoinPayload)(nil), "transactions.MintCoinPayload")
	proto.RegisterType((*Transaction)(nil), "transactions.Transaction")
	proto.RegisterEnum("transactions.TransactionType", TransactionType_name, TransactionType_value)
}

func init() { proto.RegisterFile("transactions.proto", fileDescriptor_transactions_731034eeec409a34) }

var fileDescriptor_transactions_731034eeec409a34 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0xc9, 0x6e, 0xba, 0xa5, 0xd3, 0xd2, 0x06, 0x53, 0xa1, 0x82, 0x84, 0x54, 0xe5, 0x80,
	0x2a, 0x0e, 0x0e, 0x2c, 0x37, 0xa4, 0x3d, 0xf0, 0xef, 0xc0, 0x61, 0xc5, 0xca, 0x5d, 0x2e, 0x5c,
	0xd0, 0x34, 0x98, 0xc6, 0xda, 0xd8, 0x0e, 0xf1, 0x98, 0x25, 0xdf, 0x1e, 0xd5, 0x4d, 0x44, 0xb2,
	0x1c, 0xb8, 0xf9, 0xd9, 0xe3, 0x79, 0xbf, 0x99, 0x07, 0x8c, 0x6a, 0x34, 0x0e, 0x73, 0x52, 0xd6,
	0x38, 0x5e, 0xd5, 0x96, 0x2c, 0x9b, 0xf5, 0xef, 0x9e, 0x3e, 0xd9, 0x5b, 0xbb, 0x2f, 0x65, 0x16,
	0xde, 0x76, 0xfe, 0x47, 0x86, 0xa6, 0x39, 0x16, 0xa6, 0x6f, 0x60, 0xbe, 0x95, 0xf4, 0x01, 0x09,
	0xaf, 0xb0, 0x29, 0x2d, 0x7e, 0x67, 0x0c, 0xe2, 0x0a, 0xa9, 0x58, 0x45, 0xeb, 0x68, 0x33, 0x11,
	0xe1, 0xcc, 0x96, 0x30, 0xfa, 0x85, 0xa5, 0x97, 0xab, 0x93, 0x75, 0xb4, 0x99, 0x89, 0xa3, 0x48,
	0x2f, 0xe0, 0xd1, 0x56, 0xd2, 0xe7, 0x5b, 0x23, 0x6b, 0x57, 0xa8, 0xaa, 0x6b, 0xf0, 0x1c, 0xe6,
	0xe8, 0xa9, 0x90, 0x86, 0x54, 0x8e, 0x07, 0x80, 0x55, 0xb4, 0x3e, 0xdd, 0x4c, 0xc4, 0x9d, 0xdb,
	0x94, 0x03, 0x7b, 0x6f, 0x95, 0xb9, 0xb4, 0x46, 0x12, 0xd6, 0xcd, 0x95, 0x2d, 0x55, 0xde, 0xb0,
	0x15, 0x8c, 0x35, 0xfe, 0x56, 0xda, 0xeb, 0x40, 0x10, 0x8b, 0x4e, 0xa6, 0x1e, 0x96, 0x1f, 0x1d,
	0xe1, 0xae, 0x54, 0xae, 0x38, 0x7c, 0xec, 0x01, 0x1b, 0xd4, 0xb2, 0x03, 0x3e, 0x9c, 0xd9, 0x27,
	0x58, 0xe8, 0xb6, 0xef, 0xb7, 0x2a, 0x34, 0x0e, 0xe8, 0xd3, 0xf3, 0x35, 0x1f, 0x6c, 0xeb, 0x5f,
	0x00, 0x31, 0xd7, 0x03, 0x9d, 0x5e, 0xc0, 0xe2, 0x52, 0x19, 0xfa, 0x9f, 0xe3, 0x63, 0x38, 0x43,
	0x6d, 0xbd, 0xa1, 0x60, 0x14, 0x8b, 0x56, 0xa5, 0x15, 0x4c, 0xaf, 0xff, 0x3a, 0xb2, 0x57, 0x10,
	0x53, 0x53, 0x1d, 0xbf, 0xce, 0xcf, 0x9f, 0x0d, 0x69, 0x7a, 0x85, 0xd7, 0x4d, 0x25, 0x45, 0x28,
	0x65, 0x1c, 0xc6, 0xad, 0x71, 0x3b, 0xc3, 0x92, 0x1f, 0xf3, 0xe4, 0x5d, 0x9e, 0xfc, 0xad, 0x69,
	0x44, 0x57, 0xf4, 0x42, 0xc1, 0xe2, 0x4e, 0x23, 0x36, 0x85, 0xf1, 0x17, 0x73, 0x63, 0xec, 0xad,
	0x49, 0xee, 0x1d, 0x44, 0x1b, 0x79, 0x12, 0xb1, 0x04, 0x66, 0xfd, 0x0c, 0x93, 0x13, 0xf6, 0x10,
	0x1e, 0x0c, 0xd6, 0x9c, 0x9c, 0xb2, 0x19, 0xdc, 0xef, 0x56, 0x90, 0xc4, 0x6c, 0x02, 0xa3, 0x2d,
	0xe1, 0x8d, 0x4c, 0x46, 0xef, 0x5e, 0x7e, 0xe5, 0x7b, 0x45, 0x85, 0xdf, 0xf1, 0xdc, 0xea, 0xec,
	0xa7, 0xb7, 0xb5, 0xd7, 0xb9, 0x35, 0x54, 0xdb, 0x32, 0xd3, 0xd2, 0x39, 0xdc, 0x4b, 0x97, 0xf5,
	0x47, 0xdc, 0x9d, 0x05, 0xe6, 0xd7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xed, 0x47, 0x73,
	0xb5, 0x02, 0x00, 0x00,
}
