// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/services.proto

package services // import "github.com/quorumcontrol/messages/services"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import transactions "github.com/quorumcontrol/messages/transactions"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Credentials struct {
	WalletName           string   `protobuf:"bytes,1,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	PassPhrase           string   `protobuf:"bytes,2,opt,name=pass_phrase,json=passPhrase,proto3" json:"pass_phrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{0}
}
func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (dst *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(dst, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetWalletName() string {
	if m != nil {
		return m.WalletName
	}
	return ""
}

func (m *Credentials) GetPassPhrase() string {
	if m != nil {
		return m.PassPhrase
	}
	return ""
}

type SerializableSignature struct {
	Signers              []bool   `protobuf:"varint,1,rep,packed,name=signers,proto3" json:"signers,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializableSignature) Reset()         { *m = SerializableSignature{} }
func (m *SerializableSignature) String() string { return proto.CompactTextString(m) }
func (*SerializableSignature) ProtoMessage()    {}
func (*SerializableSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{1}
}
func (m *SerializableSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializableSignature.Unmarshal(m, b)
}
func (m *SerializableSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializableSignature.Marshal(b, m, deterministic)
}
func (dst *SerializableSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializableSignature.Merge(dst, src)
}
func (m *SerializableSignature) XXX_Size() int {
	return xxx_messageInfo_SerializableSignature.Size(m)
}
func (m *SerializableSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializableSignature.DiscardUnknown(m)
}

var xxx_messageInfo_SerializableSignature proto.InternalMessageInfo

func (m *SerializableSignature) GetSigners() []bool {
	if m != nil {
		return m.Signers
	}
	return nil
}

func (m *SerializableSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SerializableSignature) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type SerializableChainTree struct {
	Dag        [][]byte                          `protobuf:"bytes,1,rep,name=dag,proto3" json:"dag,omitempty"`
	Signatures map[string]*SerializableSignature `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// tip is a string because of compatability with the javascript layer
	// which cannot seem to parse a golang cid.Bytes()
	Tip                  string   `protobuf:"bytes,3,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializableChainTree) Reset()         { *m = SerializableChainTree{} }
func (m *SerializableChainTree) String() string { return proto.CompactTextString(m) }
func (*SerializableChainTree) ProtoMessage()    {}
func (*SerializableChainTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{2}
}
func (m *SerializableChainTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializableChainTree.Unmarshal(m, b)
}
func (m *SerializableChainTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializableChainTree.Marshal(b, m, deterministic)
}
func (dst *SerializableChainTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializableChainTree.Merge(dst, src)
}
func (m *SerializableChainTree) XXX_Size() int {
	return xxx_messageInfo_SerializableChainTree.Size(m)
}
func (m *SerializableChainTree) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializableChainTree.DiscardUnknown(m)
}

var xxx_messageInfo_SerializableChainTree proto.InternalMessageInfo

func (m *SerializableChainTree) GetDag() [][]byte {
	if m != nil {
		return m.Dag
	}
	return nil
}

func (m *SerializableChainTree) GetSignatures() map[string]*SerializableSignature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *SerializableChainTree) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type RegisterWalletRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterWalletRequest) Reset()         { *m = RegisterWalletRequest{} }
func (m *RegisterWalletRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterWalletRequest) ProtoMessage()    {}
func (*RegisterWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{3}
}
func (m *RegisterWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterWalletRequest.Unmarshal(m, b)
}
func (m *RegisterWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterWalletRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWalletRequest.Merge(dst, src)
}
func (m *RegisterWalletRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterWalletRequest.Size(m)
}
func (m *RegisterWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWalletRequest proto.InternalMessageInfo

func (m *RegisterWalletRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

type RegisterWalletResponse struct {
	WalletName           string   `protobuf:"bytes,1,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterWalletResponse) Reset()         { *m = RegisterWalletResponse{} }
func (m *RegisterWalletResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterWalletResponse) ProtoMessage()    {}
func (*RegisterWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{4}
}
func (m *RegisterWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterWalletResponse.Unmarshal(m, b)
}
func (m *RegisterWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterWalletResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWalletResponse.Merge(dst, src)
}
func (m *RegisterWalletResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterWalletResponse.Size(m)
}
func (m *RegisterWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWalletResponse proto.InternalMessageInfo

func (m *RegisterWalletResponse) GetWalletName() string {
	if m != nil {
		return m.WalletName
	}
	return ""
}

type StorageAdapterConfigForBadger struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageAdapterConfigForBadger) Reset()         { *m = StorageAdapterConfigForBadger{} }
func (m *StorageAdapterConfigForBadger) String() string { return proto.CompactTextString(m) }
func (*StorageAdapterConfigForBadger) ProtoMessage()    {}
func (*StorageAdapterConfigForBadger) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{5}
}
func (m *StorageAdapterConfigForBadger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageAdapterConfigForBadger.Unmarshal(m, b)
}
func (m *StorageAdapterConfigForBadger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageAdapterConfigForBadger.Marshal(b, m, deterministic)
}
func (dst *StorageAdapterConfigForBadger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageAdapterConfigForBadger.Merge(dst, src)
}
func (m *StorageAdapterConfigForBadger) XXX_Size() int {
	return xxx_messageInfo_StorageAdapterConfigForBadger.Size(m)
}
func (m *StorageAdapterConfigForBadger) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageAdapterConfigForBadger.DiscardUnknown(m)
}

var xxx_messageInfo_StorageAdapterConfigForBadger proto.InternalMessageInfo

func (m *StorageAdapterConfigForBadger) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type StorageAdapterConfigForIpld struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offline              bool     `protobuf:"varint,2,opt,name=offline,proto3" json:"offline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageAdapterConfigForIpld) Reset()         { *m = StorageAdapterConfigForIpld{} }
func (m *StorageAdapterConfigForIpld) String() string { return proto.CompactTextString(m) }
func (*StorageAdapterConfigForIpld) ProtoMessage()    {}
func (*StorageAdapterConfigForIpld) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{6}
}
func (m *StorageAdapterConfigForIpld) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageAdapterConfigForIpld.Unmarshal(m, b)
}
func (m *StorageAdapterConfigForIpld) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageAdapterConfigForIpld.Marshal(b, m, deterministic)
}
func (dst *StorageAdapterConfigForIpld) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageAdapterConfigForIpld.Merge(dst, src)
}
func (m *StorageAdapterConfigForIpld) XXX_Size() int {
	return xxx_messageInfo_StorageAdapterConfigForIpld.Size(m)
}
func (m *StorageAdapterConfigForIpld) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageAdapterConfigForIpld.DiscardUnknown(m)
}

var xxx_messageInfo_StorageAdapterConfigForIpld proto.InternalMessageInfo

func (m *StorageAdapterConfigForIpld) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *StorageAdapterConfigForIpld) GetOffline() bool {
	if m != nil {
		return m.Offline
	}
	return false
}

type StorageAdapterConfig struct {
	// Types that are valid to be assigned to AdapterConfig:
	//	*StorageAdapterConfig_Badger
	//	*StorageAdapterConfig_Ipld
	AdapterConfig        isStorageAdapterConfig_AdapterConfig `protobuf_oneof:"adapter_config"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *StorageAdapterConfig) Reset()         { *m = StorageAdapterConfig{} }
func (m *StorageAdapterConfig) String() string { return proto.CompactTextString(m) }
func (*StorageAdapterConfig) ProtoMessage()    {}
func (*StorageAdapterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{7}
}
func (m *StorageAdapterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageAdapterConfig.Unmarshal(m, b)
}
func (m *StorageAdapterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageAdapterConfig.Marshal(b, m, deterministic)
}
func (dst *StorageAdapterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageAdapterConfig.Merge(dst, src)
}
func (m *StorageAdapterConfig) XXX_Size() int {
	return xxx_messageInfo_StorageAdapterConfig.Size(m)
}
func (m *StorageAdapterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageAdapterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StorageAdapterConfig proto.InternalMessageInfo

type isStorageAdapterConfig_AdapterConfig interface {
	isStorageAdapterConfig_AdapterConfig()
}

type StorageAdapterConfig_Badger struct {
	Badger *StorageAdapterConfigForBadger `protobuf:"bytes,1,opt,name=badger,proto3,oneof"`
}

type StorageAdapterConfig_Ipld struct {
	Ipld *StorageAdapterConfigForIpld `protobuf:"bytes,2,opt,name=ipld,proto3,oneof"`
}

func (*StorageAdapterConfig_Badger) isStorageAdapterConfig_AdapterConfig() {}

func (*StorageAdapterConfig_Ipld) isStorageAdapterConfig_AdapterConfig() {}

func (m *StorageAdapterConfig) GetAdapterConfig() isStorageAdapterConfig_AdapterConfig {
	if m != nil {
		return m.AdapterConfig
	}
	return nil
}

func (m *StorageAdapterConfig) GetBadger() *StorageAdapterConfigForBadger {
	if x, ok := m.GetAdapterConfig().(*StorageAdapterConfig_Badger); ok {
		return x.Badger
	}
	return nil
}

func (m *StorageAdapterConfig) GetIpld() *StorageAdapterConfigForIpld {
	if x, ok := m.GetAdapterConfig().(*StorageAdapterConfig_Ipld); ok {
		return x.Ipld
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StorageAdapterConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StorageAdapterConfig_OneofMarshaler, _StorageAdapterConfig_OneofUnmarshaler, _StorageAdapterConfig_OneofSizer, []interface{}{
		(*StorageAdapterConfig_Badger)(nil),
		(*StorageAdapterConfig_Ipld)(nil),
	}
}

func _StorageAdapterConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StorageAdapterConfig)
	// adapter_config
	switch x := m.AdapterConfig.(type) {
	case *StorageAdapterConfig_Badger:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Badger); err != nil {
			return err
		}
	case *StorageAdapterConfig_Ipld:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ipld); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StorageAdapterConfig.AdapterConfig has unexpected type %T", x)
	}
	return nil
}

func _StorageAdapterConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StorageAdapterConfig)
	switch tag {
	case 1: // adapter_config.badger
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StorageAdapterConfigForBadger)
		err := b.DecodeMessage(msg)
		m.AdapterConfig = &StorageAdapterConfig_Badger{msg}
		return true, err
	case 2: // adapter_config.ipld
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StorageAdapterConfigForIpld)
		err := b.DecodeMessage(msg)
		m.AdapterConfig = &StorageAdapterConfig_Ipld{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StorageAdapterConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StorageAdapterConfig)
	// adapter_config
	switch x := m.AdapterConfig.(type) {
	case *StorageAdapterConfig_Badger:
		s := proto.Size(x.Badger)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StorageAdapterConfig_Ipld:
		s := proto.Size(x.Ipld)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GenerateChainRequest struct {
	Creds                *Credentials          `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	KeyAddr              string                `protobuf:"bytes,2,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	StorageAdapter       *StorageAdapterConfig `protobuf:"bytes,3,opt,name=storage_adapter,json=storageAdapter,proto3" json:"storage_adapter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GenerateChainRequest) Reset()         { *m = GenerateChainRequest{} }
func (m *GenerateChainRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateChainRequest) ProtoMessage()    {}
func (*GenerateChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{8}
}
func (m *GenerateChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateChainRequest.Unmarshal(m, b)
}
func (m *GenerateChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateChainRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateChainRequest.Merge(dst, src)
}
func (m *GenerateChainRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateChainRequest.Size(m)
}
func (m *GenerateChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateChainRequest proto.InternalMessageInfo

func (m *GenerateChainRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *GenerateChainRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

func (m *GenerateChainRequest) GetStorageAdapter() *StorageAdapterConfig {
	if m != nil {
		return m.StorageAdapter
	}
	return nil
}

type GenerateChainResponse struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateChainResponse) Reset()         { *m = GenerateChainResponse{} }
func (m *GenerateChainResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateChainResponse) ProtoMessage()    {}
func (*GenerateChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{9}
}
func (m *GenerateChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateChainResponse.Unmarshal(m, b)
}
func (m *GenerateChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateChainResponse.Marshal(b, m, deterministic)
}
func (dst *GenerateChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateChainResponse.Merge(dst, src)
}
func (m *GenerateChainResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateChainResponse.Size(m)
}
func (m *GenerateChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateChainResponse proto.InternalMessageInfo

func (m *GenerateChainResponse) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type ExportChainRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ExportChainRequest) Reset()         { *m = ExportChainRequest{} }
func (m *ExportChainRequest) String() string { return proto.CompactTextString(m) }
func (*ExportChainRequest) ProtoMessage()    {}
func (*ExportChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{10}
}
func (m *ExportChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportChainRequest.Unmarshal(m, b)
}
func (m *ExportChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportChainRequest.Marshal(b, m, deterministic)
}
func (dst *ExportChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportChainRequest.Merge(dst, src)
}
func (m *ExportChainRequest) XXX_Size() int {
	return xxx_messageInfo_ExportChainRequest.Size(m)
}
func (m *ExportChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExportChainRequest proto.InternalMessageInfo

func (m *ExportChainRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *ExportChainRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type ExportChainResponse struct {
	ChainTree            string   `protobuf:"bytes,1,opt,name=chain_tree,json=chainTree,proto3" json:"chain_tree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportChainResponse) Reset()         { *m = ExportChainResponse{} }
func (m *ExportChainResponse) String() string { return proto.CompactTextString(m) }
func (*ExportChainResponse) ProtoMessage()    {}
func (*ExportChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{11}
}
func (m *ExportChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportChainResponse.Unmarshal(m, b)
}
func (m *ExportChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportChainResponse.Marshal(b, m, deterministic)
}
func (dst *ExportChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportChainResponse.Merge(dst, src)
}
func (m *ExportChainResponse) XXX_Size() int {
	return xxx_messageInfo_ExportChainResponse.Size(m)
}
func (m *ExportChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExportChainResponse proto.InternalMessageInfo

func (m *ExportChainResponse) GetChainTree() string {
	if m != nil {
		return m.ChainTree
	}
	return ""
}

type ImportChainRequest struct {
	Creds *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	// index 2 is a deleted key, intentionally omitted
	ChainTree            string                `protobuf:"bytes,3,opt,name=chain_tree,json=chainTree,proto3" json:"chain_tree,omitempty"`
	StorageAdapter       *StorageAdapterConfig `protobuf:"bytes,4,opt,name=storage_adapter,json=storageAdapter,proto3" json:"storage_adapter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ImportChainRequest) Reset()         { *m = ImportChainRequest{} }
func (m *ImportChainRequest) String() string { return proto.CompactTextString(m) }
func (*ImportChainRequest) ProtoMessage()    {}
func (*ImportChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{12}
}
func (m *ImportChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportChainRequest.Unmarshal(m, b)
}
func (m *ImportChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportChainRequest.Marshal(b, m, deterministic)
}
func (dst *ImportChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportChainRequest.Merge(dst, src)
}
func (m *ImportChainRequest) XXX_Size() int {
	return xxx_messageInfo_ImportChainRequest.Size(m)
}
func (m *ImportChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportChainRequest proto.InternalMessageInfo

func (m *ImportChainRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *ImportChainRequest) GetChainTree() string {
	if m != nil {
		return m.ChainTree
	}
	return ""
}

func (m *ImportChainRequest) GetStorageAdapter() *StorageAdapterConfig {
	if m != nil {
		return m.StorageAdapter
	}
	return nil
}

type ImportChainResponse struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportChainResponse) Reset()         { *m = ImportChainResponse{} }
func (m *ImportChainResponse) String() string { return proto.CompactTextString(m) }
func (*ImportChainResponse) ProtoMessage()    {}
func (*ImportChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{13}
}
func (m *ImportChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportChainResponse.Unmarshal(m, b)
}
func (m *ImportChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportChainResponse.Marshal(b, m, deterministic)
}
func (dst *ImportChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportChainResponse.Merge(dst, src)
}
func (m *ImportChainResponse) XXX_Size() int {
	return xxx_messageInfo_ImportChainResponse.Size(m)
}
func (m *ImportChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportChainResponse proto.InternalMessageInfo

func (m *ImportChainResponse) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type GenerateKeyRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GenerateKeyRequest) Reset()         { *m = GenerateKeyRequest{} }
func (m *GenerateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateKeyRequest) ProtoMessage()    {}
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{14}
}
func (m *GenerateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKeyRequest.Unmarshal(m, b)
}
func (m *GenerateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKeyRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKeyRequest.Merge(dst, src)
}
func (m *GenerateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateKeyRequest.Size(m)
}
func (m *GenerateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKeyRequest proto.InternalMessageInfo

func (m *GenerateKeyRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

type GenerateKeyResponse struct {
	KeyAddr              string   `protobuf:"bytes,1,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateKeyResponse) Reset()         { *m = GenerateKeyResponse{} }
func (m *GenerateKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateKeyResponse) ProtoMessage()    {}
func (*GenerateKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{15}
}
func (m *GenerateKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKeyResponse.Unmarshal(m, b)
}
func (m *GenerateKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKeyResponse.Marshal(b, m, deterministic)
}
func (dst *GenerateKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKeyResponse.Merge(dst, src)
}
func (m *GenerateKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateKeyResponse.Size(m)
}
func (m *GenerateKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKeyResponse proto.InternalMessageInfo

func (m *GenerateKeyResponse) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

type GetTipRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetTipRequest) Reset()         { *m = GetTipRequest{} }
func (m *GetTipRequest) String() string { return proto.CompactTextString(m) }
func (*GetTipRequest) ProtoMessage()    {}
func (*GetTipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{16}
}
func (m *GetTipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTipRequest.Unmarshal(m, b)
}
func (m *GetTipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTipRequest.Marshal(b, m, deterministic)
}
func (dst *GetTipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTipRequest.Merge(dst, src)
}
func (m *GetTipRequest) XXX_Size() int {
	return xxx_messageInfo_GetTipRequest.Size(m)
}
func (m *GetTipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTipRequest proto.InternalMessageInfo

func (m *GetTipRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *GetTipRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type GetTipResponse struct {
	Tip                  string   `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTipResponse) Reset()         { *m = GetTipResponse{} }
func (m *GetTipResponse) String() string { return proto.CompactTextString(m) }
func (*GetTipResponse) ProtoMessage()    {}
func (*GetTipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{17}
}
func (m *GetTipResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTipResponse.Unmarshal(m, b)
}
func (m *GetTipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTipResponse.Marshal(b, m, deterministic)
}
func (dst *GetTipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTipResponse.Merge(dst, src)
}
func (m *GetTipResponse) XXX_Size() int {
	return xxx_messageInfo_GetTipResponse.Size(m)
}
func (m *GetTipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTipResponse proto.InternalMessageInfo

func (m *GetTipResponse) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type ListChainIdsRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListChainIdsRequest) Reset()         { *m = ListChainIdsRequest{} }
func (m *ListChainIdsRequest) String() string { return proto.CompactTextString(m) }
func (*ListChainIdsRequest) ProtoMessage()    {}
func (*ListChainIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{18}
}
func (m *ListChainIdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListChainIdsRequest.Unmarshal(m, b)
}
func (m *ListChainIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListChainIdsRequest.Marshal(b, m, deterministic)
}
func (dst *ListChainIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListChainIdsRequest.Merge(dst, src)
}
func (m *ListChainIdsRequest) XXX_Size() int {
	return xxx_messageInfo_ListChainIdsRequest.Size(m)
}
func (m *ListChainIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListChainIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListChainIdsRequest proto.InternalMessageInfo

func (m *ListChainIdsRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

type ListChainIdsResponse struct {
	ChainIds             []string `protobuf:"bytes,1,rep,name=chain_ids,json=chainIds,proto3" json:"chain_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListChainIdsResponse) Reset()         { *m = ListChainIdsResponse{} }
func (m *ListChainIdsResponse) String() string { return proto.CompactTextString(m) }
func (*ListChainIdsResponse) ProtoMessage()    {}
func (*ListChainIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{19}
}
func (m *ListChainIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListChainIdsResponse.Unmarshal(m, b)
}
func (m *ListChainIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListChainIdsResponse.Marshal(b, m, deterministic)
}
func (dst *ListChainIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListChainIdsResponse.Merge(dst, src)
}
func (m *ListChainIdsResponse) XXX_Size() int {
	return xxx_messageInfo_ListChainIdsResponse.Size(m)
}
func (m *ListChainIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListChainIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListChainIdsResponse proto.InternalMessageInfo

func (m *ListChainIdsResponse) GetChainIds() []string {
	if m != nil {
		return m.ChainIds
	}
	return nil
}

type ListKeysRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListKeysRequest) Reset()         { *m = ListKeysRequest{} }
func (m *ListKeysRequest) String() string { return proto.CompactTextString(m) }
func (*ListKeysRequest) ProtoMessage()    {}
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{20}
}
func (m *ListKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKeysRequest.Unmarshal(m, b)
}
func (m *ListKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKeysRequest.Marshal(b, m, deterministic)
}
func (dst *ListKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKeysRequest.Merge(dst, src)
}
func (m *ListKeysRequest) XXX_Size() int {
	return xxx_messageInfo_ListKeysRequest.Size(m)
}
func (m *ListKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListKeysRequest proto.InternalMessageInfo

func (m *ListKeysRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

type ListKeysResponse struct {
	KeyAddrs             []string `protobuf:"bytes,1,rep,name=key_addrs,json=keyAddrs,proto3" json:"key_addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListKeysResponse) Reset()         { *m = ListKeysResponse{} }
func (m *ListKeysResponse) String() string { return proto.CompactTextString(m) }
func (*ListKeysResponse) ProtoMessage()    {}
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{21}
}
func (m *ListKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKeysResponse.Unmarshal(m, b)
}
func (m *ListKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKeysResponse.Marshal(b, m, deterministic)
}
func (dst *ListKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKeysResponse.Merge(dst, src)
}
func (m *ListKeysResponse) XXX_Size() int {
	return xxx_messageInfo_ListKeysResponse.Size(m)
}
func (m *ListKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListKeysResponse proto.InternalMessageInfo

func (m *ListKeysResponse) GetKeyAddrs() []string {
	if m != nil {
		return m.KeyAddrs
	}
	return nil
}

type SetOwnerRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	KeyAddr              string       `protobuf:"bytes,3,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	NewOwnerKeys         []string     `protobuf:"bytes,4,rep,name=new_owner_keys,json=newOwnerKeys,proto3" json:"new_owner_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetOwnerRequest) Reset()         { *m = SetOwnerRequest{} }
func (m *SetOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*SetOwnerRequest) ProtoMessage()    {}
func (*SetOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{22}
}
func (m *SetOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOwnerRequest.Unmarshal(m, b)
}
func (m *SetOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOwnerRequest.Marshal(b, m, deterministic)
}
func (dst *SetOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOwnerRequest.Merge(dst, src)
}
func (m *SetOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_SetOwnerRequest.Size(m)
}
func (m *SetOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetOwnerRequest proto.InternalMessageInfo

func (m *SetOwnerRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *SetOwnerRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *SetOwnerRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

func (m *SetOwnerRequest) GetNewOwnerKeys() []string {
	if m != nil {
		return m.NewOwnerKeys
	}
	return nil
}

type SetOwnerResponse struct {
	Tip                  string   `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetOwnerResponse) Reset()         { *m = SetOwnerResponse{} }
func (m *SetOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*SetOwnerResponse) ProtoMessage()    {}
func (*SetOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{23}
}
func (m *SetOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetOwnerResponse.Unmarshal(m, b)
}
func (m *SetOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetOwnerResponse.Marshal(b, m, deterministic)
}
func (dst *SetOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetOwnerResponse.Merge(dst, src)
}
func (m *SetOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_SetOwnerResponse.Size(m)
}
func (m *SetOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetOwnerResponse proto.InternalMessageInfo

func (m *SetOwnerResponse) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type SetDataRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	KeyAddr              string       `protobuf:"bytes,3,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	Path                 string       `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Value                []byte       `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetDataRequest) Reset()         { *m = SetDataRequest{} }
func (m *SetDataRequest) String() string { return proto.CompactTextString(m) }
func (*SetDataRequest) ProtoMessage()    {}
func (*SetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{24}
}
func (m *SetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataRequest.Unmarshal(m, b)
}
func (m *SetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataRequest.Marshal(b, m, deterministic)
}
func (dst *SetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataRequest.Merge(dst, src)
}
func (m *SetDataRequest) XXX_Size() int {
	return xxx_messageInfo_SetDataRequest.Size(m)
}
func (m *SetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataRequest proto.InternalMessageInfo

func (m *SetDataRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *SetDataRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *SetDataRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

func (m *SetDataRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SetDataRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetDataResponse struct {
	Tip                  string   `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataResponse) Reset()         { *m = SetDataResponse{} }
func (m *SetDataResponse) String() string { return proto.CompactTextString(m) }
func (*SetDataResponse) ProtoMessage()    {}
func (*SetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{25}
}
func (m *SetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataResponse.Unmarshal(m, b)
}
func (m *SetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataResponse.Marshal(b, m, deterministic)
}
func (dst *SetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataResponse.Merge(dst, src)
}
func (m *SetDataResponse) XXX_Size() int {
	return xxx_messageInfo_SetDataResponse.Size(m)
}
func (m *SetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataResponse proto.InternalMessageInfo

func (m *SetDataResponse) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type ResolveRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Path                 string       `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResolveRequest) Reset()         { *m = ResolveRequest{} }
func (m *ResolveRequest) String() string { return proto.CompactTextString(m) }
func (*ResolveRequest) ProtoMessage()    {}
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{26}
}
func (m *ResolveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveRequest.Unmarshal(m, b)
}
func (m *ResolveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveRequest.Marshal(b, m, deterministic)
}
func (dst *ResolveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveRequest.Merge(dst, src)
}
func (m *ResolveRequest) XXX_Size() int {
	return xxx_messageInfo_ResolveRequest.Size(m)
}
func (m *ResolveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveRequest proto.InternalMessageInfo

func (m *ResolveRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *ResolveRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *ResolveRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ResolveResponse struct {
	RemainingPath        string   `protobuf:"bytes,1,opt,name=remaining_path,json=remainingPath,proto3" json:"remaining_path,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveResponse) Reset()         { *m = ResolveResponse{} }
func (m *ResolveResponse) String() string { return proto.CompactTextString(m) }
func (*ResolveResponse) ProtoMessage()    {}
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{27}
}
func (m *ResolveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveResponse.Unmarshal(m, b)
}
func (m *ResolveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveResponse.Marshal(b, m, deterministic)
}
func (dst *ResolveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveResponse.Merge(dst, src)
}
func (m *ResolveResponse) XXX_Size() int {
	return xxx_messageInfo_ResolveResponse.Size(m)
}
func (m *ResolveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveResponse proto.InternalMessageInfo

func (m *ResolveResponse) GetRemainingPath() string {
	if m != nil {
		return m.RemainingPath
	}
	return ""
}

func (m *ResolveResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EstablishCoinRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	KeyAddr              string       `protobuf:"bytes,3,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	CoinName             string       `protobuf:"bytes,4,opt,name=coin_name,json=coinName,proto3" json:"coin_name,omitempty"`
	Maximum              uint64       `protobuf:"varint,5,opt,name=maximum,proto3" json:"maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EstablishCoinRequest) Reset()         { *m = EstablishCoinRequest{} }
func (m *EstablishCoinRequest) String() string { return proto.CompactTextString(m) }
func (*EstablishCoinRequest) ProtoMessage()    {}
func (*EstablishCoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{28}
}
func (m *EstablishCoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstablishCoinRequest.Unmarshal(m, b)
}
func (m *EstablishCoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstablishCoinRequest.Marshal(b, m, deterministic)
}
func (dst *EstablishCoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstablishCoinRequest.Merge(dst, src)
}
func (m *EstablishCoinRequest) XXX_Size() int {
	return xxx_messageInfo_EstablishCoinRequest.Size(m)
}
func (m *EstablishCoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EstablishCoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EstablishCoinRequest proto.InternalMessageInfo

func (m *EstablishCoinRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *EstablishCoinRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *EstablishCoinRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

func (m *EstablishCoinRequest) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

func (m *EstablishCoinRequest) GetMaximum() uint64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

type EstablishCoinResponse struct {
	Tip                  string   `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstablishCoinResponse) Reset()         { *m = EstablishCoinResponse{} }
func (m *EstablishCoinResponse) String() string { return proto.CompactTextString(m) }
func (*EstablishCoinResponse) ProtoMessage()    {}
func (*EstablishCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{29}
}
func (m *EstablishCoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstablishCoinResponse.Unmarshal(m, b)
}
func (m *EstablishCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstablishCoinResponse.Marshal(b, m, deterministic)
}
func (dst *EstablishCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstablishCoinResponse.Merge(dst, src)
}
func (m *EstablishCoinResponse) XXX_Size() int {
	return xxx_messageInfo_EstablishCoinResponse.Size(m)
}
func (m *EstablishCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EstablishCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EstablishCoinResponse proto.InternalMessageInfo

func (m *EstablishCoinResponse) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type MintCoinRequest struct {
	Creds                *Credentials `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string       `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	KeyAddr              string       `protobuf:"bytes,3,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	CoinName             string       `protobuf:"bytes,4,opt,name=coin_name,json=coinName,proto3" json:"coin_name,omitempty"`
	Amount               uint64       `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MintCoinRequest) Reset()         { *m = MintCoinRequest{} }
func (m *MintCoinRequest) String() string { return proto.CompactTextString(m) }
func (*MintCoinRequest) ProtoMessage()    {}
func (*MintCoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{30}
}
func (m *MintCoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintCoinRequest.Unmarshal(m, b)
}
func (m *MintCoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintCoinRequest.Marshal(b, m, deterministic)
}
func (dst *MintCoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintCoinRequest.Merge(dst, src)
}
func (m *MintCoinRequest) XXX_Size() int {
	return xxx_messageInfo_MintCoinRequest.Size(m)
}
func (m *MintCoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MintCoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MintCoinRequest proto.InternalMessageInfo

func (m *MintCoinRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *MintCoinRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *MintCoinRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

func (m *MintCoinRequest) GetCoinName() string {
	if m != nil {
		return m.CoinName
	}
	return ""
}

func (m *MintCoinRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MintCoinResponse struct {
	Tip                  string   `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MintCoinResponse) Reset()         { *m = MintCoinResponse{} }
func (m *MintCoinResponse) String() string { return proto.CompactTextString(m) }
func (*MintCoinResponse) ProtoMessage()    {}
func (*MintCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{31}
}
func (m *MintCoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintCoinResponse.Unmarshal(m, b)
}
func (m *MintCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintCoinResponse.Marshal(b, m, deterministic)
}
func (dst *MintCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintCoinResponse.Merge(dst, src)
}
func (m *MintCoinResponse) XXX_Size() int {
	return xxx_messageInfo_MintCoinResponse.Size(m)
}
func (m *MintCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MintCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MintCoinResponse proto.InternalMessageInfo

func (m *MintCoinResponse) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type PlayTransactionsRequest struct {
	Creds                *Credentials                `protobuf:"bytes,1,opt,name=creds,proto3" json:"creds,omitempty"`
	ChainId              string                      `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	KeyAddr              string                      `protobuf:"bytes,3,opt,name=key_addr,json=keyAddr,proto3" json:"key_addr,omitempty"`
	Transactions         []*transactions.Transaction `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PlayTransactionsRequest) Reset()         { *m = PlayTransactionsRequest{} }
func (m *PlayTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*PlayTransactionsRequest) ProtoMessage()    {}
func (*PlayTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{32}
}
func (m *PlayTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayTransactionsRequest.Unmarshal(m, b)
}
func (m *PlayTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayTransactionsRequest.Marshal(b, m, deterministic)
}
func (dst *PlayTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayTransactionsRequest.Merge(dst, src)
}
func (m *PlayTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_PlayTransactionsRequest.Size(m)
}
func (m *PlayTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayTransactionsRequest proto.InternalMessageInfo

func (m *PlayTransactionsRequest) GetCreds() *Credentials {
	if m != nil {
		return m.Creds
	}
	return nil
}

func (m *PlayTransactionsRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *PlayTransactionsRequest) GetKeyAddr() string {
	if m != nil {
		return m.KeyAddr
	}
	return ""
}

func (m *PlayTransactionsRequest) GetTransactions() []*transactions.Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type PlayTransactionsResponse struct {
	Tip                  string   `protobuf:"bytes,1,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayTransactionsResponse) Reset()         { *m = PlayTransactionsResponse{} }
func (m *PlayTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*PlayTransactionsResponse) ProtoMessage()    {}
func (*PlayTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_38dc57afdd005c6b, []int{33}
}
func (m *PlayTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayTransactionsResponse.Unmarshal(m, b)
}
func (m *PlayTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayTransactionsResponse.Marshal(b, m, deterministic)
}
func (dst *PlayTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayTransactionsResponse.Merge(dst, src)
}
func (m *PlayTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_PlayTransactionsResponse.Size(m)
}
func (m *PlayTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayTransactionsResponse proto.InternalMessageInfo

func (m *PlayTransactionsResponse) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

func init() {
	proto.RegisterType((*Credentials)(nil), "services.Credentials")
	proto.RegisterType((*SerializableSignature)(nil), "services.SerializableSignature")
	proto.RegisterType((*SerializableChainTree)(nil), "services.SerializableChainTree")
	proto.RegisterMapType((map[string]*SerializableSignature)(nil), "services.SerializableChainTree.SignaturesEntry")
	proto.RegisterType((*RegisterWalletRequest)(nil), "services.RegisterWalletRequest")
	proto.RegisterType((*RegisterWalletResponse)(nil), "services.RegisterWalletResponse")
	proto.RegisterType((*StorageAdapterConfigForBadger)(nil), "services.StorageAdapterConfigForBadger")
	proto.RegisterType((*StorageAdapterConfigForIpld)(nil), "services.StorageAdapterConfigForIpld")
	proto.RegisterType((*StorageAdapterConfig)(nil), "services.StorageAdapterConfig")
	proto.RegisterType((*GenerateChainRequest)(nil), "services.GenerateChainRequest")
	proto.RegisterType((*GenerateChainResponse)(nil), "services.GenerateChainResponse")
	proto.RegisterType((*ExportChainRequest)(nil), "services.ExportChainRequest")
	proto.RegisterType((*ExportChainResponse)(nil), "services.ExportChainResponse")
	proto.RegisterType((*ImportChainRequest)(nil), "services.ImportChainRequest")
	proto.RegisterType((*ImportChainResponse)(nil), "services.ImportChainResponse")
	proto.RegisterType((*GenerateKeyRequest)(nil), "services.GenerateKeyRequest")
	proto.RegisterType((*GenerateKeyResponse)(nil), "services.GenerateKeyResponse")
	proto.RegisterType((*GetTipRequest)(nil), "services.GetTipRequest")
	proto.RegisterType((*GetTipResponse)(nil), "services.GetTipResponse")
	proto.RegisterType((*ListChainIdsRequest)(nil), "services.ListChainIdsRequest")
	proto.RegisterType((*ListChainIdsResponse)(nil), "services.ListChainIdsResponse")
	proto.RegisterType((*ListKeysRequest)(nil), "services.ListKeysRequest")
	proto.RegisterType((*ListKeysResponse)(nil), "services.ListKeysResponse")
	proto.RegisterType((*SetOwnerRequest)(nil), "services.SetOwnerRequest")
	proto.RegisterType((*SetOwnerResponse)(nil), "services.SetOwnerResponse")
	proto.RegisterType((*SetDataRequest)(nil), "services.SetDataRequest")
	proto.RegisterType((*SetDataResponse)(nil), "services.SetDataResponse")
	proto.RegisterType((*ResolveRequest)(nil), "services.ResolveRequest")
	proto.RegisterType((*ResolveResponse)(nil), "services.ResolveResponse")
	proto.RegisterType((*EstablishCoinRequest)(nil), "services.EstablishCoinRequest")
	proto.RegisterType((*EstablishCoinResponse)(nil), "services.EstablishCoinResponse")
	proto.RegisterType((*MintCoinRequest)(nil), "services.MintCoinRequest")
	proto.RegisterType((*MintCoinResponse)(nil), "services.MintCoinResponse")
	proto.RegisterType((*PlayTransactionsRequest)(nil), "services.PlayTransactionsRequest")
	proto.RegisterType((*PlayTransactionsResponse)(nil), "services.PlayTransactionsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletRPCServiceClient is the client API for WalletRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletRPCServiceClient interface {
	Register(ctx context.Context, in *RegisterWalletRequest, opts ...grpc.CallOption) (*RegisterWalletResponse, error)
	GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error)
	CreateChainTree(ctx context.Context, in *GenerateChainRequest, opts ...grpc.CallOption) (*GenerateChainResponse, error)
	ExportChainTree(ctx context.Context, in *ExportChainRequest, opts ...grpc.CallOption) (*ExportChainResponse, error)
	ImportChainTree(ctx context.Context, in *ImportChainRequest, opts ...grpc.CallOption) (*ImportChainResponse, error)
	GetTip(ctx context.Context, in *GetTipRequest, opts ...grpc.CallOption) (*GetTipResponse, error)
	ListChainIds(ctx context.Context, in *ListChainIdsRequest, opts ...grpc.CallOption) (*ListChainIdsResponse, error)
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
	SetOwner(ctx context.Context, in *SetOwnerRequest, opts ...grpc.CallOption) (*SetOwnerResponse, error)
	SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*SetDataResponse, error)
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	EstablishCoin(ctx context.Context, in *EstablishCoinRequest, opts ...grpc.CallOption) (*EstablishCoinResponse, error)
	MintCoin(ctx context.Context, in *MintCoinRequest, opts ...grpc.CallOption) (*MintCoinResponse, error)
}

type walletRPCServiceClient struct {
	cc *grpc.ClientConn
}

func NewWalletRPCServiceClient(cc *grpc.ClientConn) WalletRPCServiceClient {
	return &walletRPCServiceClient{cc}
}

func (c *walletRPCServiceClient) Register(ctx context.Context, in *RegisterWalletRequest, opts ...grpc.CallOption) (*RegisterWalletResponse, error) {
	out := new(RegisterWalletResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error) {
	out := new(GenerateKeyResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/GenerateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) CreateChainTree(ctx context.Context, in *GenerateChainRequest, opts ...grpc.CallOption) (*GenerateChainResponse, error) {
	out := new(GenerateChainResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/CreateChainTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) ExportChainTree(ctx context.Context, in *ExportChainRequest, opts ...grpc.CallOption) (*ExportChainResponse, error) {
	out := new(ExportChainResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/ExportChainTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) ImportChainTree(ctx context.Context, in *ImportChainRequest, opts ...grpc.CallOption) (*ImportChainResponse, error) {
	out := new(ImportChainResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/ImportChainTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) GetTip(ctx context.Context, in *GetTipRequest, opts ...grpc.CallOption) (*GetTipResponse, error) {
	out := new(GetTipResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/GetTip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) ListChainIds(ctx context.Context, in *ListChainIdsRequest, opts ...grpc.CallOption) (*ListChainIdsResponse, error) {
	out := new(ListChainIdsResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/ListChainIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/ListKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) SetOwner(ctx context.Context, in *SetOwnerRequest, opts ...grpc.CallOption) (*SetOwnerResponse, error) {
	out := new(SetOwnerResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/SetOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*SetDataResponse, error) {
	out := new(SetDataResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/SetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/Resolve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) EstablishCoin(ctx context.Context, in *EstablishCoinRequest, opts ...grpc.CallOption) (*EstablishCoinResponse, error) {
	out := new(EstablishCoinResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/EstablishCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletRPCServiceClient) MintCoin(ctx context.Context, in *MintCoinRequest, opts ...grpc.CallOption) (*MintCoinResponse, error) {
	out := new(MintCoinResponse)
	err := c.cc.Invoke(ctx, "/services.WalletRPCService/MintCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletRPCServiceServer is the server API for WalletRPCService service.
type WalletRPCServiceServer interface {
	Register(context.Context, *RegisterWalletRequest) (*RegisterWalletResponse, error)
	GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyResponse, error)
	CreateChainTree(context.Context, *GenerateChainRequest) (*GenerateChainResponse, error)
	ExportChainTree(context.Context, *ExportChainRequest) (*ExportChainResponse, error)
	ImportChainTree(context.Context, *ImportChainRequest) (*ImportChainResponse, error)
	GetTip(context.Context, *GetTipRequest) (*GetTipResponse, error)
	ListChainIds(context.Context, *ListChainIdsRequest) (*ListChainIdsResponse, error)
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	SetOwner(context.Context, *SetOwnerRequest) (*SetOwnerResponse, error)
	SetData(context.Context, *SetDataRequest) (*SetDataResponse, error)
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	EstablishCoin(context.Context, *EstablishCoinRequest) (*EstablishCoinResponse, error)
	MintCoin(context.Context, *MintCoinRequest) (*MintCoinResponse, error)
}

func RegisterWalletRPCServiceServer(s *grpc.Server, srv WalletRPCServiceServer) {
	s.RegisterService(&_WalletRPCService_serviceDesc, srv)
}

func _WalletRPCService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).Register(ctx, req.(*RegisterWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/GenerateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).GenerateKey(ctx, req.(*GenerateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_CreateChainTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).CreateChainTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/CreateChainTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).CreateChainTree(ctx, req.(*GenerateChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_ExportChainTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).ExportChainTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/ExportChainTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).ExportChainTree(ctx, req.(*ExportChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_ImportChainTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).ImportChainTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/ImportChainTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).ImportChainTree(ctx, req.(*ImportChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_GetTip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).GetTip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/GetTip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).GetTip(ctx, req.(*GetTipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_ListChainIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChainIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).ListChainIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/ListChainIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).ListChainIds(ctx, req.(*ListChainIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/ListKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_SetOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).SetOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/SetOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).SetOwner(ctx, req.(*SetOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_SetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).SetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/SetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).SetData(ctx, req.(*SetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/Resolve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_EstablishCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstablishCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).EstablishCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/EstablishCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).EstablishCoin(ctx, req.(*EstablishCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletRPCService_MintCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletRPCServiceServer).MintCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.WalletRPCService/MintCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletRPCServiceServer).MintCoin(ctx, req.(*MintCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletRPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.WalletRPCService",
	HandlerType: (*WalletRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WalletRPCService_Register_Handler,
		},
		{
			MethodName: "GenerateKey",
			Handler:    _WalletRPCService_GenerateKey_Handler,
		},
		{
			MethodName: "CreateChainTree",
			Handler:    _WalletRPCService_CreateChainTree_Handler,
		},
		{
			MethodName: "ExportChainTree",
			Handler:    _WalletRPCService_ExportChainTree_Handler,
		},
		{
			MethodName: "ImportChainTree",
			Handler:    _WalletRPCService_ImportChainTree_Handler,
		},
		{
			MethodName: "GetTip",
			Handler:    _WalletRPCService_GetTip_Handler,
		},
		{
			MethodName: "ListChainIds",
			Handler:    _WalletRPCService_ListChainIds_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _WalletRPCService_ListKeys_Handler,
		},
		{
			MethodName: "SetOwner",
			Handler:    _WalletRPCService_SetOwner_Handler,
		},
		{
			MethodName: "SetData",
			Handler:    _WalletRPCService_SetData_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _WalletRPCService_Resolve_Handler,
		},
		{
			MethodName: "EstablishCoin",
			Handler:    _WalletRPCService_EstablishCoin_Handler,
		},
		{
			MethodName: "MintCoin",
			Handler:    _WalletRPCService_MintCoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/services.proto",
}

func init() { proto.RegisterFile("services/services.proto", fileDescriptor_services_38dc57afdd005c6b) }

var fileDescriptor_services_38dc57afdd005c6b = []byte{
	// 1228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x6d, 0x4f, 0x1b, 0xc7,
	0x13, 0xcf, 0x61, 0x07, 0x9b, 0x31, 0xb1, 0xd1, 0x02, 0xc1, 0x38, 0xe1, 0x41, 0xfb, 0x4f, 0xf4,
	0xa7, 0x6d, 0x84, 0x23, 0xd3, 0x4a, 0x6d, 0xa3, 0x46, 0x32, 0x0e, 0x25, 0x94, 0xf0, 0xa0, 0x33,
	0x52, 0xa4, 0xaa, 0xaa, 0xb5, 0xf8, 0x16, 0xb3, 0xe2, 0x7c, 0x77, 0xd9, 0x5d, 0x43, 0xdc, 0x8f,
	0x52, 0xa9, 0xaf, 0xdb, 0xbc, 0xeb, 0xfb, 0x7e, 0x81, 0x7e, 0x98, 0x7e, 0x88, 0xea, 0xf6, 0xf6,
	0xec, 0x3d, 0xfb, 0x0c, 0x12, 0x41, 0x51, 0xdf, 0xed, 0xc3, 0xcc, 0x6f, 0x7e, 0x33, 0xb3, 0x37,
	0x33, 0x36, 0x2c, 0x09, 0xca, 0x2f, 0x59, 0x9b, 0x8a, 0x6a, 0xbc, 0xd8, 0x0c, 0xb8, 0x2f, 0x7d,
	0x94, 0x8f, 0xf7, 0x95, 0x35, 0xc9, 0x89, 0x27, 0x48, 0x5b, 0x32, 0xdf, 0x13, 0x55, 0x73, 0x13,
	0x89, 0xe2, 0x23, 0x28, 0x34, 0x38, 0x75, 0xa8, 0x27, 0x19, 0x71, 0x05, 0x5a, 0x83, 0xc2, 0x15,
	0x71, 0x5d, 0x2a, 0x5b, 0x1e, 0xe9, 0xd2, 0xb2, 0xb5, 0x6e, 0x6d, 0xcc, 0xd8, 0x10, 0x1d, 0x1d,
	0x92, 0x2e, 0x0d, 0x05, 0x02, 0x22, 0x44, 0x2b, 0x38, 0xe7, 0x44, 0xd0, 0xf2, 0x54, 0x24, 0x10,
	0x1e, 0x1d, 0xab, 0x13, 0xdc, 0x86, 0xc5, 0x26, 0xe5, 0x8c, 0xb8, 0xec, 0x17, 0x72, 0xea, 0xd2,
	0x26, 0xeb, 0x78, 0x44, 0xf6, 0x38, 0x45, 0x65, 0xc8, 0x09, 0xd6, 0xf1, 0x28, 0x17, 0x65, 0x6b,
	0x3d, 0xb3, 0x91, 0xb7, 0xe3, 0x2d, 0x7a, 0x0c, 0x33, 0x22, 0x16, 0x53, 0x88, 0xb3, 0xf6, 0xf0,
	0x00, 0x21, 0xc8, 0xca, 0x7e, 0x40, 0xcb, 0x19, 0x65, 0x4a, 0xad, 0xf1, 0x3f, 0x56, 0xd2, 0x4a,
	0xe3, 0x9c, 0x30, 0xef, 0x84, 0x53, 0x8a, 0xe6, 0x20, 0xe3, 0x90, 0x8e, 0xb2, 0x30, 0x6b, 0x87,
	0x4b, 0x74, 0x04, 0x30, 0x00, 0x13, 0xe5, 0xa9, 0xf5, 0xcc, 0x46, 0xa1, 0x56, 0xdd, 0x1c, 0x44,
	0x2c, 0x15, 0x66, 0x73, 0x40, 0x5b, 0xec, 0x78, 0x92, 0xf7, 0x6d, 0x03, 0x22, 0x34, 0x21, 0x59,
	0xa0, 0xf9, 0x84, 0xcb, 0xca, 0xcf, 0x50, 0x1a, 0x51, 0x08, 0x85, 0x2e, 0x68, 0x5f, 0x07, 0x30,
	0x5c, 0xa2, 0xaf, 0xe0, 0xfe, 0x25, 0x71, 0x7b, 0x91, 0x87, 0x85, 0xda, 0x5a, 0x3a, 0x85, 0x01,
	0x8e, 0x1d, 0x49, 0x7f, 0x3b, 0xf5, 0xb5, 0x85, 0x5f, 0xc1, 0xa2, 0x4d, 0x3b, 0x4c, 0x48, 0xca,
	0xdf, 0xaa, 0x54, 0xd8, 0xf4, 0x5d, 0x8f, 0x0a, 0x89, 0xbe, 0x80, 0xfb, 0x6d, 0x4e, 0x1d, 0xa1,
	0xec, 0x14, 0x6a, 0x8b, 0x43, 0x4c, 0x23, 0xa9, 0x76, 0x24, 0x83, 0xbf, 0x81, 0x87, 0xa3, 0x28,
	0x22, 0xf0, 0x3d, 0x41, 0x6f, 0xcc, 0x3a, 0xde, 0x82, 0x95, 0xa6, 0xf4, 0x39, 0xe9, 0xd0, 0xba,
	0x43, 0x02, 0x49, 0x79, 0xc3, 0xf7, 0xce, 0x58, 0xe7, 0x7b, 0x9f, 0x6f, 0x13, 0xa7, 0x43, 0x79,
	0x98, 0xa4, 0x80, 0xc8, 0x73, 0xad, 0xaa, 0xd6, 0x78, 0x1f, 0x1e, 0x4d, 0x50, 0xda, 0x0b, 0x5c,
	0x27, 0x4d, 0x25, 0x7c, 0x23, 0xfe, 0xd9, 0x99, 0xcb, 0xbc, 0x28, 0x4a, 0x79, 0x3b, 0xde, 0xe2,
	0x3f, 0x2c, 0x58, 0x48, 0x43, 0x43, 0x75, 0x98, 0x3e, 0x55, 0x1c, 0x74, 0x0c, 0xfe, 0x6f, 0xc4,
	0xf5, 0x3a, 0xca, 0xaf, 0xef, 0xd9, 0x5a, 0x11, 0xbd, 0x80, 0x2c, 0x0b, 0x5c, 0x47, 0x27, 0xe6,
	0xe9, 0x8d, 0x00, 0x21, 0xfd, 0xd7, 0xf7, 0x6c, 0xa5, 0xb4, 0x3d, 0x07, 0x45, 0x12, 0xdd, 0xb7,
	0xda, 0x4a, 0x00, 0xff, 0x6e, 0xc1, 0xc2, 0x2e, 0xf5, 0x28, 0x27, 0x32, 0x7a, 0x51, 0xb7, 0xc9,
	0x16, 0x5a, 0x86, 0xfc, 0x05, 0xed, 0xb7, 0x88, 0xe3, 0x70, 0xfd, 0x95, 0xe5, 0x2e, 0x68, 0xbf,
	0xee, 0x38, 0x1c, 0xed, 0x42, 0x49, 0x44, 0xcc, 0x5a, 0xda, 0xb4, 0x7a, 0x8c, 0x85, 0xda, 0xea,
	0xf5, 0xd4, 0xed, 0xa2, 0x48, 0x9c, 0xe2, 0x1a, 0x2c, 0x8e, 0x10, 0xd5, 0x0f, 0x62, 0x19, 0xf2,
	0xed, 0xf0, 0xa0, 0xc5, 0x1c, 0x9d, 0x9f, 0x9c, 0xda, 0xef, 0x39, 0xf8, 0x27, 0x40, 0x3b, 0xef,
	0x03, 0x9f, 0xcb, 0x8f, 0x72, 0x6d, 0x80, 0x3e, 0x95, 0x44, 0xff, 0x12, 0xe6, 0x13, 0xe8, 0x9a,
	0xcf, 0x0a, 0x40, 0xa4, 0x21, 0x39, 0x8d, 0xdf, 0xe7, 0x4c, 0x3b, 0xfe, 0x5a, 0xf1, 0x07, 0x0b,
	0xd0, 0x5e, 0xf7, 0xe3, 0x48, 0x25, 0x4d, 0x64, 0x46, 0x4c, 0xa4, 0xc5, 0x3c, 0x7b, 0xab, 0x98,
	0x3f, 0x87, 0xf9, 0x04, 0xd5, 0x9b, 0x23, 0x5e, 0x07, 0x14, 0x67, 0x69, 0x9f, 0xf6, 0x6f, 0xf5,
	0xe9, 0x3f, 0x87, 0xf9, 0x04, 0xc4, 0xd0, 0xe8, 0xe0, 0x8d, 0x59, 0x89, 0x37, 0x86, 0xdf, 0xc2,
	0x83, 0x5d, 0x2a, 0x4f, 0x58, 0x70, 0xd7, 0x19, 0xc6, 0x50, 0x8c, 0x81, 0x35, 0x0b, 0x5d, 0x4f,
	0xad, 0x41, 0x3d, 0xc5, 0xdb, 0x30, 0xff, 0x86, 0x89, 0x28, 0x42, 0x7b, 0x8e, 0xb8, 0x95, 0xcb,
	0x5b, 0xb0, 0x90, 0xc4, 0xd0, 0xd6, 0x1e, 0xc1, 0x4c, 0x4c, 0x2d, 0x6a, 0x44, 0x33, 0x76, 0x5e,
	0x73, 0x13, 0xf8, 0x25, 0x94, 0x42, 0xa5, 0x7d, 0xda, 0xbf, 0x9d, 0xd1, 0x2a, 0xcc, 0x0d, 0xf5,
	0x87, 0x06, 0xe3, 0x20, 0x0f, 0x0c, 0xea, 0x28, 0x0b, 0xfc, 0xab, 0x05, 0xa5, 0x26, 0x95, 0x47,
	0x57, 0x1e, 0xe5, 0x77, 0x1c, 0xe9, 0x44, 0x76, 0x33, 0xc9, 0x0a, 0xf2, 0x04, 0x8a, 0x1e, 0xbd,
	0x6a, 0xf9, 0xa1, 0xd9, 0xd6, 0x05, 0xed, 0x8b, 0x72, 0x56, 0x11, 0x9b, 0xf5, 0xe8, 0x95, 0xe2,
	0x12, 0x7a, 0x80, 0x9f, 0xc0, 0xdc, 0x90, 0xdb, 0xc4, 0x64, 0xfd, 0x66, 0x41, 0xb1, 0x49, 0xe5,
	0x2b, 0x22, 0xc9, 0x27, 0xf4, 0x20, 0xee, 0x1e, 0x59, 0xa3, 0x7b, 0x2c, 0xc4, 0x1d, 0xf6, 0xbe,
	0x9a, 0x21, 0xa2, 0x0d, 0xfe, 0x9f, 0x8a, 0x70, 0x44, 0x6f, 0xa2, 0x13, 0x2e, 0x14, 0x6d, 0x2a,
	0x7c, 0xf7, 0x92, 0xde, 0xb5, 0x0f, 0x31, 0xd1, 0x8c, 0xd1, 0x19, 0xdf, 0x40, 0x69, 0x60, 0x4d,
	0x53, 0x7a, 0x0a, 0x45, 0x4e, 0xbb, 0x84, 0x79, 0xcc, 0xeb, 0xb4, 0x8c, 0xbe, 0xf8, 0x60, 0x70,
	0x7a, 0x1c, 0xba, 0x88, 0x20, 0xeb, 0x10, 0x49, 0xf4, 0x94, 0xa4, 0xd6, 0xf8, 0x4f, 0x0b, 0x16,
	0x76, 0x84, 0x24, 0xa7, 0x2e, 0x13, 0xe7, 0x0d, 0xff, 0xce, 0x8b, 0xf2, 0x75, 0x69, 0x08, 0xbf,
	0x26, 0x9f, 0x79, 0xd1, 0xdc, 0x10, 0xe5, 0x22, 0x1f, 0x1e, 0xa8, 0x59, 0xb1, 0x0c, 0xb9, 0x2e,
	0x79, 0xcf, 0xba, 0xbd, 0xae, 0xca, 0x48, 0xd6, 0x8e, 0xb7, 0xf8, 0x33, 0x58, 0x1c, 0x61, 0x3c,
	0x31, 0x33, 0x1f, 0x2c, 0x28, 0x1d, 0x30, 0x4f, 0xfe, 0x97, 0x1c, 0x7b, 0x08, 0xd3, 0xa4, 0xeb,
	0xf7, 0x3c, 0xa9, 0xfd, 0xd2, 0xbb, 0xf0, 0x83, 0x19, 0x52, 0x9d, 0xe8, 0xd1, 0x5f, 0x16, 0x2c,
	0x1d, 0xbb, 0xa4, 0x7f, 0x62, 0x4c, 0xe3, 0x9f, 0xd0, 0xb3, 0xef, 0x60, 0xd6, 0xfc, 0x1d, 0xa0,
	0xbe, 0xfc, 0x42, 0x6d, 0x79, 0x33, 0xf1, 0xe3, 0xc0, 0xe0, 0x66, 0x27, 0xc4, 0xf1, 0x33, 0x28,
	0x8f, 0x93, 0x9f, 0xe4, 0x6b, 0xed, 0xef, 0x1c, 0xcc, 0xe9, 0x61, 0xf3, 0xb8, 0xd1, 0x8c, 0x7c,
	0x41, 0x07, 0x90, 0x8f, 0x07, 0x51, 0x64, 0x8c, 0xc1, 0xa9, 0x23, 0x6e, 0x65, 0x7d, 0xb2, 0x80,
	0xb6, 0xfa, 0x03, 0x14, 0x8c, 0xe6, 0x86, 0x1e, 0x0f, 0x15, 0xc6, 0xdb, 0x66, 0x65, 0x65, 0xc2,
	0xad, 0xc6, 0xb2, 0xa1, 0xd4, 0xe0, 0x34, 0x9e, 0x87, 0x54, 0xe7, 0x5f, 0x1d, 0xd7, 0x30, 0xa7,
	0x8c, 0xca, 0xda, 0xc4, 0x7b, 0x8d, 0x79, 0x08, 0x25, 0x63, 0xa6, 0x51, 0x98, 0x06, 0xc7, 0xf1,
	0x61, 0xca, 0xe4, 0x98, 0x36, 0x0c, 0x1d, 0x42, 0xc9, 0x98, 0x20, 0x46, 0xf1, 0xc6, 0xe7, 0x20,
	0x13, 0x2f, 0x6d, 0xf4, 0x78, 0x01, 0xd3, 0x51, 0x47, 0x46, 0x4b, 0xa6, 0x2b, 0x46, 0xf3, 0xaf,
	0x94, 0xc7, 0x2f, 0xb4, 0xf2, 0x01, 0xcc, 0x9a, 0x6d, 0x16, 0x19, 0xb6, 0x52, 0x5a, 0x78, 0x65,
	0x75, 0xd2, 0xb5, 0x86, 0xab, 0x43, 0x3e, 0x6e, 0xa0, 0x68, 0x39, 0x29, 0x6b, 0x34, 0xe5, 0x4a,
	0x25, 0xed, 0x6a, 0x08, 0x11, 0x77, 0x2d, 0x13, 0x62, 0xa4, 0xcb, 0x9a, 0x10, 0x63, 0x4d, 0xee,
	0x25, 0xe4, 0x74, 0xcb, 0x40, 0xe5, 0x84, 0x98, 0xd1, 0xe4, 0x2a, 0xcb, 0x29, 0x37, 0x43, 0x7d,
	0x5d, 0xdf, 0x4d, 0xfd, 0x64, 0x83, 0x31, 0xf5, 0x47, 0x9b, 0xc1, 0x31, 0x3c, 0x48, 0x94, 0x47,
	0xf3, 0x0d, 0xa6, 0x55, 0x7a, 0xf3, 0x0d, 0xa6, 0xd7, 0xd5, 0x3a, 0xe4, 0xe3, 0xca, 0x64, 0x06,
	0x65, 0xa4, 0xb0, 0x9a, 0x41, 0x19, 0x2d, 0x64, 0xdb, 0xcf, 0x7e, 0xfc, 0xbc, 0xc3, 0xe4, 0x79,
	0xef, 0x74, 0xb3, 0xed, 0x77, 0xab, 0xef, 0x7a, 0x3e, 0xef, 0x75, 0xdb, 0xbe, 0x27, 0xb9, 0xef,
	0x56, 0xbb, 0x54, 0x08, 0xd2, 0x31, 0xfe, 0x88, 0x38, 0x9d, 0x56, 0x7f, 0x2f, 0x6c, 0xfd, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x40, 0xc6, 0x4d, 0x53, 0xa4, 0x10, 0x00, 0x00,
}
