name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - uses: actions/setup-node@v1
      with:
        node-version: '13.5.0'
    - name: checkout messages
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: diff protobuf & generated code
      run: make diff
    - name: run Go code tests
      run: make test
